version: '2'

volumes:
    api:
  
services:
  
    wall-e_api:
        build: ./api
        expose:
            - 80
        volumes:
            - api:/app
        environment:
            GUNICORN_CMD_ARGS: --reload
        restart: unless-stopped
