version: '3'
  
services:
  
    wall-e_php:
        build:
            context: ./docker/php
        expose:
            - 9000
        volumes:
            - ./html:/var/www/
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        restart: unless-stopped
  
    wall-e_nginx:
        image: nginx:latest
        expose:
            - 80
        volumes:
            - ./html:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - wall-e_php
        environment:
            VIRTUAL_HOST: localhost
            LETSENCRYPT_HOST: localhost
        restart: unless-stopped
  
    wall-e_api:
        build: ./docker/api
        expose:
            - 80
        volumes:
            - ./api:/app
        depends_on:
            - toxsense_db
        environment:
            VIRTUAL_HOST: api.localhost
            LETSENCRYPT_HOST: api.localhost
            GUNICORN_CMD_ARGS: --reload
        restart: unless-stopped          

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./nginx-proxy/certs:/etc/nginx/certs:ro
          - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
          - ./nginx-proxy/html:/usr/share/nginx/html
          - ./nginx-proxy/conf.d:/etc/nginx/conf.d
        environment:
          - ENABLE_IPV6=true

networks:
  default:
    external:
      name: nginx-proxy
