version: '2'
  
services:
  
    wall-e_api:
        build: ./api
        privileged: true
        ports:
            - 80:80
        environment:
            GUNICORN_CMD_ARGS: --reload
        restart: unless-stopped
