#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/movie2serial.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-aarch64.jar:$APPDIR/lib/gluegen-rt-natives-linux-aarch64.jar:$APPDIR/lib/gst1-java-core-1.2.0.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/video.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar" movie2serial "$@"
