version: '3'
  
services:  
    swzpln:
        container_name: wall-e_ui
        image: php:apache
        ports:
            - 8080:80
        volumes:
            - ./html:/var/www/html
        environment:
            - APIURL=https://8b30755028eb3126a5ec52785b2826b4.balena-devices.com
        restart: "no"
