version: '3'
  
services:  
    swzpln:
        container_name: wall-e_ui
        image: php:apache
        ports:
            - 8080:80
        volumes:
            - ./html:/var/www/html
        environment:
            - APIURL=http://api.localhost
        restart: "no"