version: '3'
  
services:  
    wall-e_ui:
        container_name: wall-e_ui
        image: php:apache
        ports:
            - 8080:80
        volumes:
            - ./html:/var/www/html
        environment:
            - APIURL=https://ac6fe026fa8d0b9d8afea0ebaed5a778.balena-devices.com/api
            - password=hallo_wall-e
        restart: "no"
