version: '2'

volumes:
    qMovies:
    movDB:

  
services:
  
    wall-e_api:
        build: .
        privileged: true
        ports:
            - 80:80
        volumes:
            - 'qMovies:/app/qMovies'
            - 'movDB:/app/movDB'
        environment:
            GUNICORN_CMD_ARGS: --reload
        restart: unless-stopped
